### ISSUE TITLE
Example configuration deletes assembly and minimap results

### ISSUE THREAD

**Issue by jguhlin** [shingocat/agisps#12]
No warning message, XML configuration taken from GitHub page.... Default should be to not erase things.

**Comment by shingocat** [comment]
Hi jgnhlin,

LRScaf would build a new folder specified by the output parameters if not existed. And if the output folder is existed,  it will delete the conents under this folder since LRScaf needs to manipulate these output files before. 
Sorry for bring unconvenient. We have update a new version LRScaf.1.1.8.jar to build and renew only the output files of LRScaf.
