### ISSUE TITLE
Output and parameters

### ISSUE THREAD

**Issue by ptranvan** [shingocat/agisps#19]
Hi @shingocat 

I got a few questions about the output files and program in general:

1) In the file `contig_coverage.info`, I have some contigs that are missing but are present in the final scaffolding. What does that mean ?

2) Some of my contigs are also not present in the final scaffold assembly (I just grep the contig in `nodePaths.info `and it doesn't exist) Even if it can't be scaffolded, I would expect a single scaffold composed of one contig. Why these contigs are not present at the end ? ( I see that there is a mapping result on the minimap2 file)

3) What contain the file `repeat.contigs `? 

4) I am not sure to understand the `min_supported_links` parameter: if it is set at 1, does it mean that it needs 1 pacbio reads that overlap between 2 contigs for the scaffolding ? What is the `min_supported_links` optimal parameter for 25X of PacBio reads ?

5) Do you gap-fill the final assembly, or it just performed a scaffolding ?

**Comment by shingocat** [comment]
Hi ptranvan,

1) LRScaf calculates the coverages for a contig only if a contigs is covered completely by long reads. This makes the difference between the original  set of contigs and the set of contigs in contig_coverages.info file.  If the length of a contig is much large than long reads, it might be not in the contig_coverage.info file. 
2) LRScaf has a parameter "min_contig_length" to filter the small contigs. The filtered contigs would be not in the final scaffols. The smaller contigs have multi-alignment and complex the assembly graph. If you want to keep them, you chould change the filter parameters. 
3) as mentioned in point 1, if the coverage of a contig is over than the  [mean + 3sd] of coverage distribution, it will be considered as a repeat contig.
4) LRScaf has a validation model to validate the link between two contigs, not just a long read connects two contigs will be considered as a link.  LRScaf is designed for low-coverage and has validation model for alignment. The min_supported_links of 1 is fine for 25X. If you want more accuracy outcomes, you could set it to be 2.
5) If two contigs is supported to be overlap, LRScaf does a local alignment to connect them. Otherwise, N would be filled in the gap. Since LRScaf is designed for low coverages and in most of cases, it has only one link between two contigs. LRScaf does not do the gap-filling procedule.

**Comment by ptranvan** [comment]
Thanks @shingocat 

1) Is it related to the `miniOLRatio` parameter ? so If a contig is covered by >= `miniOLRatio`, then it's reported ?

2) I used default parameter for minimum contig length (200 bp) and all my original contigs have a size of >= 1000bp so I am not affected by this parameter. Is there any other reason why the contigs are filtered out ? (by looking at the minimap2 file, I can see some mapping results) 

3) Is [mean + 3sd]  related to iqr_time which is by default at 1.5 and does that mean I should rise it to 3 ?

**Comment by shingocat** [comment]
Hi ptranvan,

This is one of the parameter for the validation model. After validated by model, if the contig was not the node in the assembly graph, it will be not included in the finally outcomes. 
Yes, higher iqr_time value will increase the repeat standard.

**Comment by ptranvan** [comment]
1) Hi @shingocat. Thanks but it's not clear to me. How the model validate that a contig is not a node in  the assembly graph ? based of which criteria ?  

2) In `nodePaths.info`, I see come scaffolds composed of one contigs. example:

```
digraph G8327{
ctg085354;
}
```
No problem. But in the final fasta file some scaffolds (composed of one contig) are present but not in `nodePaths.info`. Why ? example:

```
tail *fasta

>Scaffolds_14776  ctg089584 1012
```
But when I `grep` `ctg089584` in `nodePaths.info`, there is no result. Why ?

3) Can you please explain the options `maOHLen` `maELen` `tiplength`. I read the wiki  but it's not clear for me.

**Comment by shingocat** [comment]
Hi, ptranvan,

For the validation model, LRScaf considers the overlap length, over-hang length of two end, alignment identity. The long read should bridged two contigs. This information will be used in the assembly graph as edges and nodes.

maOHLen is overhang length of contig when a long read aligment to it, meaning the ending of a contig is not fully match the long read.
maELen is used to define the ending of long reads, there are different circumstance for using this information to filter alingments.
You could image alignment between contigs and long reads as this ">----<", they match in the middle, however have dissimilarity on the ending.  For different circumstances have been descript in the LRScaf paper. 

Tiplength is a tip on the assembly graph, when a linear path has a short branch. 

Nodepaths.info is the information for recording the paths in the assembly graph. And the final scaffolds include all scaffolds and contigs except the repeats.
